version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine
        PM2_VERSION: latest
    image: "${DOCKER_USERNAME}/nestjs-app:${VERSION}" # Tagging by version
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
