services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION} # Build version from your GitHub Actions or environment
    image: '${DOCKER_USERNAME}/nestjs-app:${VERSION}' # Tagged by version
    ports:
      - '3000:3000' # Exposing port 3000 for Nest.js
    environment:
      NODE_ENV: production
    env_file:
      - .env # Load environment variables from .env file
    restart: unless-stopped
