version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine
        PM2_VERSION: latest
        VERSION: ${VERSION}
    image: '${DOCKER_USERNAME}/nestjs-app:${VERSION}' # Tagged by version
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      # Only mount volumes in development mode
      - .:/app:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    
