name: Backend Deployment with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (needed for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Get version from package.json
      - name: Get version from package.json
        id: version_info
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 5: Build, Tag, and Push Docker images using Docker Compose
      - name: Build, Tag, and Push Docker image
        run: |
          # Define environment variables
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export VERSION=${{ env.VERSION }}
          
          # Build the image with Docker Compose
          docker compose -f ./docker-compose.yml build

          # Tag the image with 'latest' and version-specific tag
          docker tag $DOCKER_USERNAME/nestjs-app:$VERSION $DOCKER_USERNAME/nestjs-app:latest

          # Push both tags to Docker Hub
          docker push $DOCKER_USERNAME/nestjs-app:$VERSION
          docker push $DOCKER_USERNAME/nestjs-app:latest

      # Step 6: SSH into EC2 instance and deploy with Docker Compose
      - name: SSH and deploy Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Exit on any failure

            # Define environment variables for Docker Compose on EC2
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export VERSION=${{ env.VERSION }}

            # Pull the latest Docker images from Docker Hub
            echo "Deploying Docker image with version $VERSION..."
            sudo docker compose -f ./docker-compose.yml pull

            # Stop
