name: Backend Deployment with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (needed for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Get version from package.json
      - name: Get version from package.json
        id: version_info
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 5: Build and Push Docker images using Docker Compose
      - name: Build and Push Docker image
        run: |
          # Build the images
          docker-compose -f ../docker-compose.yml build

          # Tagging the image with latest and specific version
          docker tag ${DOCKER_USERNAME}/nestjs-app:latest ${DOCKER_USERNAME}/nestjs-app:${{ env.VERSION }}
          
          # Push the images to Docker Hub
          docker-compose -f ../docker-compose.yml push
          docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

      # Step 6: SSH into EC2 instance and handle deployment
      - name: SSH and deploy Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Exit on any failure

            # Pull the latest Docker images from Docker Hub
            echo "Deploying Docker image with version ${{ env.VERSION }}..."
            sudo docker-compose -f ../docker-compose.yml pull

            # Stop and remove any existing containers
            sudo docker-compose -f ../docker-compose.yml down || true

            # Start the application with Docker Compose
            sudo docker-compose -f ../docker-compose.yml up -d
            echo "Deployment complete."

      # Step 7: Rollback on failure
      - name: Rollback on failure
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deployment failed, rolling back to previous version..."
            sudo docker-compose -f ../docker-compose.yml down || true
            
            # Assuming the last working version is tagged as 'latest'
            sudo docker-compose -f ../docker-compose.yml pull
            sudo docker-compose -f ../docker-compose.yml up -d
            echo "Rollback complete."
